Name:           perl-MooX-Aliases
Version:        0.001006
Release:        2%{?dist}
Summary:        Easy aliasing of methods and attributes in Moo
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MooX-Aliases/
Source0:        http://www.cpan.org/authors/id/H/HA/HAARG/MooX-Aliases-%{version}.tar.gz
#Source1:        https://github.com/p5sagit/Distar/archive/master.zip
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(Class::Method::Modifiers) >= 1.05
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moo) >= 1.001
BuildRequires:  perl(strictures) >= 1
BuildRequires:  perl(Test::Fatal) >= 0.003
BuildRequires:  perl(Test::More) >= 0.94
BuildRequires:  wget
BuildRequires:  perl(Test::CleanNamespaces)
Requires:       perl(Class::Method::Modifiers) >= 1.05
Requires:       perl(Moo) >= 1.001
Requires:       perl(strictures) >= 1
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The MooX::Aliases module will allow you to quickly alias methods in Moo. It
provides an alias parameter for has() to generate aliased accessors as well
as the standard ones. Attributes can also be initialized in the constructor
via their aliased names.

%prep
%setup -q -n MooX-Aliases-%{version}
wget https://github.com/p5sagit/Distar/archive/master.zip
unzip master.zip
mv Distar-master Distar


%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Jun 09 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.001006-1
- New COPR release
* Thu Jun 09 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.001006-1
- Specfile autogenerated by cpanspec 1.78.
